### ISSUE TITLE
the image is cut

### ISSUE THREAD

**Issue by Atheraf3** [zavierferodova/Google-Drive-View-Only-PDF-Script-Downloader#1]
each page of the PDF is enlarged so it looks like it's cut off

**Comment by zavierferodova** [comment]
Hey there, I'm sorry. Are you already follow the instruction on readme ? Or maybe you can provide the example ?

**Comment by Atheraf3** [comment]
Oh, it's all solved.

Pada Sel, 26 Nov 2024, 9.34 PM, Zavier Ferodova Al Fitroh <
***@***.***> menulis:
